spring:
  application:
    name: listing-service

  datasource:
    url: jdbc:postgresql://localhost:5432/listings_db
    username: postgres
    password: Gelnova4ev

  jpa:
    hibernate:
      ddl: validate

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      listing-events: listing-events

outbox:
  scheduler:
    delay: 5000