package ru.romzheln.listing.model.enums;

public enum EventType {
  CREATED,
  UPDATED,
  REMOVED,
  PRICE_CHANGED,
  UPDATED_PROPERTY,
  PROMOTION_ADDED,
  PROMOTION_DISABLED,
  MORTGAGE_PROGRAM_ADDED,
  MORTGAGE_PROGRAMS_REMOVED,
  PUBLISHED,
  ARCHIVED,
  APPROVED,
  IMAGES_ADDED,
  IMAGES_REMOVED,
  UPDATED_DEVELOPER,
  UPDATED_LAND_USE,
  UPDATED_COMPLEX,
  CREATED_COMMUNICATION,
  UPDATED_COMMUNICATION,
  CREATED_PURPOSE,
  UPDATED_PURPOSE
}
